CREATE TABLE TALLER(
	ID_TALLER NUMERIC(6) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR2(120) NOT NULL,
	DESCRIPCION VARCHAR2(280) NOT NULL,
	ESTADO CHAR(1) DEFAULT '1' NOT NULL
);

CREATE SEQUENCE SEQ_TALLER;

INSERT INTO TALLER(ID_TALLER,NOMBRE,DESCRIPCION) VALUES(SEQ_TALLER.NEXTVAL,'Spring Boot','Ejemplos básicos');
INSERT INTO TALLER(ID_TALLER,NOMBRE,DESCRIPCION) VALUES(SEQ_TALLER.NEXTVAL,'Angular 11','Arquitectura y mejoras');

COMMIT;